// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqxbgkcwojoakpqatcia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xeGJna2N3b2pvYWtwcWF0Y2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjU2MzcsImV4cCI6MjA3MDI0MTYzN30.2EAXxP9Ig4aKP3hihT_M_GvQicnV6NoDgwyX5MzyXvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});